name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: SSH into AWS EC2 and execute commands
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@3.91.207.90 << 'EOF'
          ls
          pwd
          mkdir test
          
        EOF
